from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from uuid import UUID


@dataclass(frozen=True, slots=True)
class BatchPortalProbeOutcome:
    batch_id: UUID
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    authenticated: bool
    contracting_menu_found: bool
    enter_contract_found: bool
    assistant_access_found: bool
    duration_ms: int
    checked_at: datetime


@dataclass(frozen=True, slots=True)
class BatchAssistantProbeOutcome:
    batch_id: UUID
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    authenticated: bool
    assistant_opened: bool
    assistant_container_found: bool
    record_type_found: bool
    contract_number_found: bool
    contractor_search_found: bool
    project_search_found: bool
    validate_button_found: bool
    missing_controls: tuple[str, ...]
    duration_ms: int
    checked_at: datetime


@dataclass(frozen=True, slots=True)
class BatchHeaderDraftProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    contractor_document: str
    contractor_nature: str
    project_code: str
    authenticated: bool
    assistant_opened: bool
    record_type_selected: bool
    contract_number_written: bool
    contractor_dialog_opened: bool
    contractor_nature_selected: bool
    contractor_document_written: bool
    contractor_result_found: bool
    contractor_selected: bool
    project_dialog_opened: bool
    project_code_written: bool
    project_result_found: bool
    project_selected: bool
    validate_button_found: bool
    validate_clicked: bool
    duration_ms: int
    checked_at: datetime

@dataclass(frozen=True, slots=True)
class BatchGeneralDataDraftProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    contractor_document: str
    contractor_nature: str
    project_code: str
    object_description: str
    signing_date: str
    starting_date: str
    amount: str
    term_days: int
    process_type: str
    procedure: str
    contract_type: str
    authenticated: bool
    assistant_opened: bool
    header_validation_confirmed: bool
    object_written: bool
    signing_date_written: bool
    starting_date_written: bool
    amount_written: bool
    amount_in_words_generated: bool
    contract_term_written: bool
    term_unit_days_selected: bool
    process_type_selected: bool
    procedure_selected: bool
    contract_type_selected: bool
    other_currency_no_selected: bool
    general_data_completed: bool
    general_validate_clicked: bool
    save_clicked: bool
    duration_ms: int
    checked_at: datetime


@dataclass(frozen=True, slots=True)
class BatchGeneralCompletionDraftProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    contractor_document: str
    contractor_nature: str
    project_code: str
    budget_year: int
    budget_item: str
    budget_subsector: str
    secop_url: str
    execution_department: str
    execution_city: str
    authenticated: bool
    assistant_opened: bool
    header_validation_confirmed: bool
    general_data_completed: bool
    government_plan_selected: bool
    budget_year_selected: bool
    budget_item_selected: bool
    budget_subsector_selected: bool
    budget_link_clicked: bool
    secop_yes_selected: bool
    secop_url_written: bool
    advance_no_selected: bool
    commercial_trust_no_selected: bool
    urgency_no_selected: bool
    future_commitment_no_selected: bool
    cooperation_contract_no_selected: bool
    execution_department_selected: bool
    execution_city_selected: bool
    final_validate_button_found: bool
    general_completion_completed: bool
    general_validate_clicked: bool
    save_clicked: bool
    duration_ms: int
    checked_at: datetime


@dataclass(frozen=True, slots=True)
class BatchGeneralValidationProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    contractor_document: str
    contractor_nature: str
    project_code: str
    authenticated: bool
    assistant_opened: bool
    header_validation_confirmed: bool
    general_data_completed: bool
    general_completion_completed: bool
    final_validate_button_found: bool
    general_validate_clicked: bool
    general_validation_confirmed: bool
    save_button_found: bool
    save_clicked: bool
    duration_ms: int
    checked_at: datetime


@dataclass(frozen=True, slots=True)
class BatchContractSaveProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    contractor_document: str
    contractor_nature: str
    project_code: str
    amount: str
    authenticated: bool
    assistant_opened: bool
    header_validation_confirmed: bool
    general_data_completed: bool
    general_completion_completed: bool
    general_validation_confirmed: bool
    save_button_found: bool
    save_clicked: bool
    success_dialog_found: bool
    success_dialog_accepted: bool
    contract_saved_confirmed: bool
    supervisor_section_found: bool
    duration_ms: int
    checked_at: datetime


@dataclass(frozen=True, slots=True)
class BatchContractSupervisorLinkProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    supervisor_document: str
    supervisor_type: str
    amount: str
    authenticated: bool
    assistant_opened: bool
    contract_saved_confirmed: bool
    supervisor_section_found: bool
    supervisor_dialog_opened: bool
    supervisor_nature_selected: bool
    supervisor_id_type_selected: bool
    supervisor_document_written: bool
    supervisor_result_found: bool
    supervisor_selected: bool
    supervisor_type_internal_confirmed: bool
    supervisor_validate_clicked: bool
    supervisor_validation_confirmed: bool
    supervisor_link_clicked: bool
    success_dialog_found: bool
    success_dialog_accepted: bool
    supervisor_linked_confirmed: bool
    availability_section_found: bool
    duration_ms: int
    checked_at: datetime


@dataclass(frozen=True, slots=True)
class BatchHeaderValidationProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    contractor_document: str
    contractor_nature: str
    project_code: str
    authenticated: bool
    assistant_opened: bool
    record_type_selected: bool
    contract_number_written: bool
    contractor_selected: bool
    project_selected: bool
    validate_button_found: bool
    validate_clicked: bool
    header_validation_confirmed: bool
    general_data_ready: bool
    general_object_found: bool
    general_signing_date_found: bool
    general_starting_date_found: bool
    general_amount_found: bool
    general_contract_term_found: bool
    missing_controls: tuple[str, ...]
    save_clicked: bool
    duration_ms: int
    checked_at: datetime



@dataclass(frozen=True, slots=True)
class BatchContractAvailabilityLinkProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    supervisor_document: str
    supervisor_type: str
    cdp_code: str
    amount: str
    authenticated: bool
    assistant_opened: bool
    contract_saved_confirmed: bool
    supervisor_section_found: bool
    supervisor_dialog_opened: bool
    supervisor_nature_selected: bool
    supervisor_id_type_selected: bool
    supervisor_document_written: bool
    supervisor_result_found: bool
    supervisor_selected: bool
    supervisor_type_internal_confirmed: bool
    supervisor_validate_clicked: bool
    supervisor_validation_confirmed: bool
    supervisor_link_clicked: bool
    supervisor_success_dialog_found: bool
    supervisor_success_dialog_accepted: bool
    supervisor_linked_confirmed: bool
    availability_section_found: bool
    availability_search_written: bool
    availability_result_found: bool
    availability_result_matches: bool
    availability_link_clicked: bool
    availability_link_success_found: bool
    availability_linked_row_confirmed: bool
    continue_button_found: bool
    continue_clicked: bool
    budget_register_section_found: bool
    duration_ms: int
    checked_at: datetime

@dataclass(frozen=True, slots=True)
class BatchContractBudgetRegisterLinkProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    supervisor_document: str
    cdp_code: str
    budget_register_number: str
    budget_register_date: str | None
    gross_total: str
    amount: str
    authenticated: bool
    assistant_opened: bool
    contract_saved_confirmed: bool
    supervisor_linked_confirmed: bool
    availability_linked_row_confirmed: bool
    budget_register_section_found: bool
    budget_register_number_written: bool
    budget_register_date_provided: bool
    budget_register_date_written: bool
    budget_register_availability_selected: bool
    gross_total_written: bool
    budget_register_validate_clicked: bool
    budget_register_validation_confirmed: bool
    budget_register_link_clicked: bool
    budget_register_success_dialog_found: bool
    budget_register_success_dialog_accepted: bool
    budget_register_linked_confirmed: bool
    additional_dates_section_found: bool
    duration_ms: int
    checked_at: datetime

@dataclass(frozen=True, slots=True)
class BatchContractAdditionalDatesLinkProbeOutcome:
    batch_id: UUID
    item_id: UUID
    row_number: int
    dependency: str
    probe_name: str
    success: bool
    code: str
    message: str
    contract_number: str
    cdp_code: str
    budget_register_number: str
    guarantee_approval_date: str | None
    website_publication_date: str | None
    secop_publication_date: str | None
    amount: str
    authenticated: bool
    assistant_opened: bool
    contract_saved_confirmed: bool
    supervisor_linked_confirmed: bool
    availability_linked_row_confirmed: bool
    budget_register_linked_confirmed: bool
    additional_dates_section_found: bool
    additional_dates_any_provided: bool
    guarantee_approval_date_provided: bool
    guarantee_approval_date_written: bool
    website_publication_date_provided: bool
    website_publication_date_written: bool
    secop_publication_date_provided: bool
    secop_publication_date_written: bool
    additional_dates_validate_clicked: bool
    additional_dates_validation_confirmed: bool
    additional_dates_link_clicked: bool
    additional_dates_success_dialog_found: bool
    additional_dates_success_dialog_accepted: bool
    additional_dates_skipped: bool
    additional_dates_linked_confirmed: bool
    file_reported_section_found: bool
    duration_ms: int
    checked_at: datetime

